// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7CWCHkaE1qqlkw0QKIWIgDr-hyN6lrUk',
    appId: '1:246106334934:web:9ba407130f41a20d8e8b77',
    messagingSenderId: '246106334934',
    projectId: 'group-introduce-app',
    authDomain: 'group-introduce-app.firebaseapp.com',
    storageBucket: 'group-introduce-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeMo8Gbddtzju4xch_7COSEaX9Wgf9R8k',
    appId: '1:246106334934:android:f968f0d43b40f2fb8e8b77',
    messagingSenderId: '246106334934',
    projectId: 'group-introduce-app',
    storageBucket: 'group-introduce-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVjMAtLzlJVs_Xea63ub_OSMCIFOLuD9g',
    appId: '1:246106334934:ios:78b38a3ef04c61ba8e8b77',
    messagingSenderId: '246106334934',
    projectId: 'group-introduce-app',
    storageBucket: 'group-introduce-app.appspot.com',
    iosClientId: '246106334934-7kb7c7l8qmam23bm33c5v5fqjulo7goe.apps.googleusercontent.com',
    iosBundleId: 'com.example.groupIntroduceProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVjMAtLzlJVs_Xea63ub_OSMCIFOLuD9g',
    appId: '1:246106334934:ios:6f899b4e297007e08e8b77',
    messagingSenderId: '246106334934',
    projectId: 'group-introduce-app',
    storageBucket: 'group-introduce-app.appspot.com',
    iosClientId: '246106334934-edr643np7jegj8tknsu2se068fvdmu1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.groupIntroduceProject.RunnerTests',
  );
}
